config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
  resources :conversations do
    # member do
    #   get :messages
    # end
    collection do
      get :start_convo
    end
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'

  has_many :messages, dependent: :destroy

  def other_user(user)
    another_user = convo_users - [user]
    another_user.first
  end

  def convo_users
    [sender, receiver]
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sent_conversations, class_name: 'Conversation', foreign_key: 'sender_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'receiver_id'

  has_one_attached :profile_picture

  def full_name
    "#{first_name} #{last_name}"
  end

  def conversations
    sent_conversations + received_conversations
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_user, only: [:start_convo]

  def show
  	@convo = Conversation.find(params[:id])
    @messages = @convo.messages.where.not(body: nil).order(:desc)
    @message = @convo.messages.new
  end

  def start_convo
    @convo = find_or_create_conversation
    redirect_to conversation_path(@convo)
  end

  def messages
    @convo = Conversation.find(params[:id])
    @messages = @convo.messages.order(:desc)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def find_or_create_conversation
    Conversation.find_by(
      "(sender_id = :current_user_id AND receiver_id = :user_id) OR (sender_id = :user_id AND receiver_id = :current_user_id)",
      current_user_id: current_user.id,
      user_id: @user.id
    ) || Conversation.create(sender_id: current_user.id, receiver_id: @user.id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :set_conversation

	def index
		@convo = Conversation.find(params[:conversation_id])
		@message = @convo.messages.new
		@messages = @convo.messages.where.not(body: nil)
	end

	def create
		message = @convo.messages.create(message_params)
		Turbo::StreamsChannel.broadcast_append_to(
      "conversation_#{@convo.id}_#{current_user.id}",
      partial: "messages/message",
      target:  "messages",
      locals:  { message: message, whos_msg: 'end', play_noti: false}
    )
    Turbo::StreamsChannel.broadcast_append_to(
      "conversation_#{@convo.id}_#{@convo.other_user(current_user).id}",
      partial: "messages/message",
      target:  "messages",
      locals:  { message: message, whos_msg: 'start', play_noti: true}
    )

    Turbo::StreamsChannel.broadcast_replace_to(
      "conversation_uniq_#{@convo.id}",
      partial: "messages/last_msg",
      target:  "convo_#{@convo.id}_last_msg",
      locals:  { convo: @convo}
    )
	end

	private
	def set_conversation
		@convo = Conversation.find(params[:conversation_id])
	end

	def message_params
		params.require(:message).permit(:user_id, :body)
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	
	def show
		@room = Room.find(params[:id])
	end

	def new
		@room = Room.new
	end

	def create
		@room = Room.new(room_params)
		if @room.save
			redirect_to @room
		else
			render :new
		end
	end

	private
	def room_params
		params.require(:room).permit(:name)
	end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	def new
		super
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @convos = current_user.conversations
    @users = User.where.not(id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def present_user
		current_user
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/conversations/_conversation.html.erb
<section style="height: 90%; overflow: auto;">
	<section style="height: 10%;" class="mb-3">	
		<%= render 'shared/navbar', title: convo.other_user(current_user).full_name, logout_btn: false%>
	</section>
	<%= turbo_stream_from "conversation_#{convo.id}" %>
	<%= turbo_stream_from "conversation_#{convo.id}_#{current_user.id}" %>
	<section id="messages" style="height: 90%">
		<% @messages&.each do |message|%>
			<% whos_msg = message.user == current_user ? 'end' : 'start'%>
			<%= render 'messages/message', message: message, whos_msg: whos_msg, play_noti: false%>
		<%end%>
	</section>
</section>
<section style="height: 10%;">
	<%= form_with model: message, url: conversation_messages_path(convo), html: {id: 'message-form', class: 'd-flex'} do |f| %>
		<%= hidden_field_tag :conversation_id, convo.id%>
		<%= f.hidden_field :user_id, value: current_user.id%>
		<div class="input-group">
			<%= f.text_area :body, class: 'form-control', style: "width: 500px; height: auto; min-height: 1.5em;"%>
		</div>
			<%= f.submit 'send', class: 'btn btn-primary sent_btn'%>
	<%end%>
</section>


<script type="text/javascript">
	$(document).ready(function() {
    $('#message-form').on('submit', function(event) {
      event.preventDefault();

      var form = $(this);
      var url = form.attr('action');

      $.ajax({
        type: 'POST',
        url: url,
        data: form.serialize(),
        success: function(response) {
          $('#message_body').val('');
          $('.sent_btn').prop('disabled', false);
        },
        error: function(xhr, status, error) {
          console.error('Form submission failed: ', status, error);
        }
      });
  	});
  });
</script>

app/views/conversations/show.html.erb
<div class="row">
	<section style="width: 30%;">
		<%= render 'shared/conversations', convos: current_user.conversations - [@convo]%>
	</section>
	<section style="width: 70%; height: 600px;" class="border rounded">
		<div id="convo_body" style="height: 100%;"></div>
	</section>
</div>

app/views/conversations/start_convo.js.erb
$("#convo_body").html('<%= j render "conversation", convo: @convo, message: @message %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllInOne</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <style type="text/css">
      .profile-picture{
        width: 50px;
      }
      .list-group a{
        text-decoration: none;
      }
    </style>
  </head>

  <body class="container p-3">
    <%= render 'shared/navbar', title: 'Chat App', logout_btn: true%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script type="text/javascript">
      function playNotificationSound() {
        const audio = new Audio("<%= asset_path('Podda.mp3')%>");
        $(audio).on('error', function(event) {
          console.log('Audio playback failed:', event);
        });
        audio.play();
      }
    </script>
  </body>
</html>

app/views/messages/_last_msg.html.erb
<span id="convo_<%=convo.id%>_last_msg">
	<%convo_msgs = convo.messages.where.not(body: nil)%>
	<p class="mx-2"><%= convo_msgs.present? ? convo_msgs.last.body : 'No Message Till...'%></p>
</span>

app/views/messages/_message.html.erb
<div class="message d-flex flex-column align-items-<%= whos_msg%>">
	<p class="p-2 border rounded" style="width: fit-content;"><%= message.body %></p>
</div>
<% if play_noti %>
  <script type="text/javascript">
    playNotificationSound();
  </script>
<% end %>

app/views/messages/index.js.erb
$("#convo_body").html('<%= j render "conversations/conversation", convo: @convo, message: @message %>');

app/views/shared/_conversations.html.erb
<ul class="list-group">
	<%= turbo_stream_from "conversation_uniq_#{@convo.id}" %>
	<%= link_to conversation_messages_path(@convo), remote: true do %>
		<%user = @convo.other_user(current_user)%>
		<div class="list-group-item users">
	  	<div class="user_name d-flex">
	  		<div class="avatar">
		  		<% if user.profile_picture.attached? %>
					  <%= image_tag user.profile_picture, class: "profile-picture" %>
					<% else %>
					  <%= image_tag 'default-avatar.png', class: "profile-picture" %> <!-- Replace with your default image -->
					<% end %>
	  		</div>
	  		<div class="content">
		  		<strong class="mx-2"><%= user.full_name %></strong>
		  		<%=render 'messages/last_msg', convo: @convo%>
	  		</div>
	  	</div>
	  </div>
 	<%end%>
	<% convos.each do |convo|%>
		<%user = convo.other_user(current_user)%>
		<%= link_to conversation_messages_path(convo), remote: true do %>
		  <div class="list-group-item users">
		  	<div class="user_name d-flex">
		  		<div class="avatar">
			  		<% if user.profile_picture.attached? %>
						  <%= image_tag user.profile_picture, class: "profile-picture" %>
						<% else %>
						  <%= image_tag 'default-avatar.png', class: "profile-picture" %> <!-- Replace with your default image -->
						<% end %>
		  		</div>
		  		<div class="content">
			  		<strong class="mx-2"><%= user.full_name %></strong>
			  		<%=render 'messages/last_msg', convo: convo%>
		  		</div>
		  	</div>
		  </div>
		 <%end%>
	<%end%>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= title == 'Chat App' ? root_path : '#'%>"><%= title%></a>
    <% if user_signed_in? && logout_btn %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to log out?' }, class: 'btn btn-danger' %>
    <% end %>
  </div>
</nav>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<div class="row mb-5">
	<% @users.each do |user|%>
	  <div class="col">
			<div class="card" style="width: 18rem;">
			  <div class="card-body d-flex">
			  	<% if user.profile_picture.attached? %>
					  <%= image_tag user.profile_picture, class: "profile-picture mx-2" %>
					<% else %>
					  <%= image_tag 'default-avatar.png', class: "profile-picture mx-2" %> <!-- Replace with your default image -->
					<% end %>
			    <h5 class="card-title mt-2"><%= user.full_name%></h5>
			  </div>
			   <%= link_to 'Message', start_convo_conversations_path(user_id: user.id), class: "btn btn-primary users"%>
			</div>
		</div>
	<%end%>
</div>